name: hvandenbergh
favicon: null
layout_spectrum: 0.5294436337426305
typography_spectrum: 0.6205245123710483
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7984039701987058
  lightness: 0.35227930126711726
  saturation: 0.1500778121408075
  rhythmicContrast: 0.3308171897660941
purpose: []
