name: hvandenbergh
favicon: null
layout_spectrum: 0.74888
typography_spectrum: 0
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72369632-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1a1a1a'
    - '#ae3e26'
    - '#848982'
    - '#fdb61e'
  brandStrength: 0
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
